# Generated by Django 4.0.6 on 2022-07-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField(blank=True)),
                ('summary', models.TextField(help_text='Enter your summary', max_length=1024)),
                ('email', models.EmailField(max_length=256)),
                ('github_member', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(help_text='Enter project description', max_length=1000)),
                ('github_project', models.URLField(max_length=256)),
                ('members', models.ManyToManyField(to='api.member')),
            ],
        ),
    ]
