# Generated by Django 4.0.6 on 2022-08-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_language_member_programming_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='programming_language',
            field=models.ManyToManyField(to='api.language'),
        ),
        migrations.AddField(
            model_name='member',
            name='specialization',
            field=models.ManyToManyField(to='api.specialization'),
        ),
        migrations.AddField(
            model_name='project',
            name='specialization',
            field=models.ManyToManyField(to='api.specialization'),
        ),
    ]
