# Generated by Django 4.0.6 on 2022-10-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_project_members_alter_sociallinks_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo_url',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
